export const PROFILE = {
  firstName: "Idan",
  lastName: "Avioz",
  tagline: "Electronics \u00b7 IoT \u00b7 Embedded Systems",
  bio: "Designing, building, and testing hardware from the ground up. Every project here was soldered, debugged, and brought to life by hand.",
  aboutText: "I am an Electrical Engineering and Physics student who lives at the intersection of hardware and software. Every project here was physically built and tested, from soldering components to debugging firmware with an oscilloscope. I believe the best way to understand a system is to build it from scratch, fail, and iterate until it works.",
  email: "eavioz@gmail.com",
  linkedin: "https://www.linkedin.com/in/idan-avioz-0300703b4/",
  github: "",
  cvUrl: "",
};

export const SKILLS = [
  { id: "s1", name: "Python", category: "Programming" },
  { id: "s2", name: "Arduino & Embedded C/C++", category: "Programming" },
  { id: "s3", name: "Arduino IDE", category: "Programming" },
  { id: "s4", name: "ESP32 / IoT", category: "Programming" },
  { id: "s5", name: "Sensor Integration", category: "Electronics" },
  { id: "s6", name: "DC Motors & Servo Control", category: "Electronics" },
  { id: "s7", name: "Stepper Motors", category: "Electronics" },
  { id: "s8", name: "Basic Circuit Design", category: "Electronics" },
  { id: "s9", name: "LED Systems & Addressable Strips", category: "Electronics" },
  { id: "s10", name: "Wireless Communication (RF, BT)", category: "Communication" },
  { id: "s11", name: "Cellular & Smartphone Control", category: "Communication" },
  { id: "s12", name: "Remote Control Systems", category: "Communication" },
  { id: "s13", name: "IoT Cloud Connectivity", category: "Communication" },
  { id: "s14", name: "Robot Design & Assembly", category: "Robotics" },
  { id: "s15", name: "Motion Systems (Linear & Rotary)", category: "Robotics" },
  { id: "s16", name: "Smart Device Development", category: "Robotics" },
  { id: "s17", name: "Real-Time Audio & Sound FX", category: "Creative" },
  { id: "s18", name: "3D Modeling & Printing", category: "Fabrication" },
];

export const PROJECTS = [
  {
    id: "proj-1",
    title: "4WD Smart Car \u2014 Arduino Multi-Mode Vehicle",
    category: "Robotics",
    thumbnail: "/projects/smart-car-cover.jpg.png",
    videoUrl: [
      "https://youtube.com/shorts/o8OCKY2Ujgg",
      "https://youtube.com/shorts/cm4n-C2ftyQ",
    ],
    media: [
      "/projects/smart-car-complete.jpg",
      "/projects/smart-car-assembly.jpg",
      "/projects/smart-car-wiring.jpg",
    ],
    summary: "Built a 4WD Arduino car from scratch with three control modes: IR remote, autonomous driving with ultrasonic obstacle avoidance, and Bluetooth smartphone control via the Dabble app.",
    description: "Fully assembled and wired a 4-wheel-drive smart car from a component kit, including mechanical assembly of the dual-layer acrylic chassis, mounting four DC gear motors with T-brackets, and wiring everything according to a detailed circuit diagram. The car is powered by an Arduino UNO with an expansion board, an L298N H-bridge motor driver for independent motor control, an ultrasonic distance sensor for obstacle detection, a TM1637 digital display, a buzzer, and a voltage regulator. The project involved three distinct firmware configurations: first, IR remote control mode using an infrared receiver and a handheld remote; second, an autonomous driving mode where the car navigates on its own using the ultrasonic sensor to detect and avoid obstacles; and third, Bluetooth control mode where the IR receiver is swapped for a Bluetooth module (BT05), allowing full control from a smartphone via the Dabble app. Each mode required uploading different code to the Arduino along with installing the appropriate libraries (IRremote, TM1637, Dabble). All wiring was done by hand using jumper cables connected to terminal blocks and the expansion board \u2014 no soldering required.",
    techStack: ["Arduino UNO", "C++", "L298N H-Bridge", "DC Gear Motors", "IR Remote Control", "Bluetooth (BT05)", "Ultrasonic Sensor", "TM1637 Display", "Arduino IDE", "Dabble App"],
    challenges: [
      { problem: "Motors spinning in the wrong direction after assembly due to factory wiring variations", solution: "Identified mismatched motors by testing each one individually, then swapped the red and black wire connections at the H-bridge terminals to reverse the affected motor's direction while keeping it on the same output pins." },
      { problem: "Wiring 19+ jumper cables correctly between the expansion board, H-bridge, sensors, display, and voltage regulator", solution: "Followed the circuit diagram pin-by-pin, paying close attention to the S/G/V row labels on the expansion board, and verified each connection before powering on to avoid damaging components." },
      { problem: "Switching between IR remote and Bluetooth control modes", solution: "Physically disconnected the IR receiver, connected the Bluetooth module (BT05) in its place following a separate wiring diagram, uploaded the Bluetooth firmware, installed the Dabble library, and paired the phone via the Dabble app's Gamepad interface." },
    ],
    specs: {
      "Microcontroller": "Arduino UNO + Expansion Board",
      "Motor Driver": "L298N Dual H-Bridge",
      "Motors": "4x DC Gear Motors",
      "Distance Sensor": "Ultrasonic (HC-SR04)",
      "Display": "TM1637 4-Digit Digital",
      "Control Modes": "IR Remote / Autonomous / Bluetooth",
      "Bluetooth": "BT05 Module + Dabble App",
      "Power": "6x AA Batteries (car) + 2x AAA (remote)",
      "Libraries": "IRremote, TM1637, Dabble",
    },
    github: "",
  },
];
