export const PROFILE = {
  firstName: "Idan",
  lastName: "Avioz",
  tagline: "Electronics \u00b7 IoT \u00b7 Embedded Systems",
  bio: "Designing, building, and testing hardware from the ground up. Every project here was soldered, debugged, and brought to life by hand.",
  aboutText: "I am an Electrical Engineering and Physics student who lives at the intersection of hardware and software. Every project here was physically built and tested, from soldering components to debugging firmware with an oscilloscope. I believe the best way to understand a system is to build it from scratch, fail, and iterate until it works.",
  email: "eavioz@gmail.com",
  linkedin: "https://www.linkedin.com/in/idan-avioz-0300703b4/",
  github: "",
  cvUrl: "",
};

export const SKILLS = [
  { id: "s1", name: "Python", category: "Programming" },
  { id: "s2", name: "Arduino & Embedded C/C++", category: "Programming" },
  { id: "s3", name: "Arduino IDE", category: "Programming" },
  { id: "s4", name: "ESP32 / IoT", category: "Programming" },
  { id: "s5", name: "Sensor Integration", category: "Electronics" },
  { id: "s6", name: "DC Motors & Servo Control", category: "Electronics" },
  { id: "s7", name: "Stepper Motors", category: "Electronics" },
  { id: "s8", name: "Basic Circuit Design", category: "Electronics" },
  { id: "s9", name: "LED Systems & Addressable Strips", category: "Electronics" },
  { id: "s10", name: "Wireless Communication (RF, BT)", category: "Communication" },
  { id: "s11", name: "Cellular & Smartphone Control", category: "Communication" },
  { id: "s12", name: "Remote Control Systems", category: "Communication" },
  { id: "s13", name: "IoT Cloud Connectivity", category: "Communication" },
  { id: "s14", name: "Robot Design & Assembly", category: "Robotics" },
  { id: "s15", name: "Motion Systems (Linear & Rotary)", category: "Robotics" },
  { id: "s16", name: "Smart Device Development", category: "Robotics" },
  { id: "s17", name: "Real-Time Audio & Sound FX", category: "Creative" },
  { id: "s18", name: "3D Modeling & Printing", category: "Fabrication" },
];

export const PROJECTS = [
  {
    id: "proj-1",
    title: "4WD Smart Car \u2014 Arduino Autonomous Vehicle",
    category: "Robotics",
    thumbnail: "/projects/smart-car-cover.jpg.png",
    videoUrl: "https://youtube.com/shorts/o8OCKY2Ujgg",
    media: [
      "/projects/smart-car-complete.jpg",
      "/projects/smart-car-assembly.jpg",
      "/projects/smart-car-wiring.jpg",
    ],
    summary: "Built a 4-wheel-drive smart car from scratch using Arduino UNO, H-bridge motor driver, and mecanum wheels \u2014 capable of omnidirectional movement and obstacle avoidance.",
    description: "Designed and assembled a fully functional 4WD smart car as part of an Arduino robotics course. The build started from bare components: a blue acrylic dual-layer chassis, four yellow DC gear motors with mecanum wheels for omnidirectional movement, and an L298N H-bridge motor driver for independent speed and direction control of each motor. The Arduino UNO serves as the brain, running custom C++ firmware written in the Arduino IDE. The project progressed through multiple phases \u2014 from basic LED blinking and sensor interfacing to full motor control logic, wiring the H-bridge, and integrating the complete drive system. Each motor is independently controllable via PWM signals, enabling forward, reverse, lateral, and rotational movement patterns.",
    techStack: ["Arduino UNO", "C++", "L298N H-Bridge", "DC Gear Motors", "Mecanum Wheels", "Arduino IDE"],
    challenges: [
      { problem: "Wiring four motors to the H-bridge with correct polarity for each wheel", solution: "Systematically tested each motor individually, labeled all wires, and used a color-coded wiring scheme to prevent polarity errors during assembly." },
      { problem: "Motors spinning at different speeds causing the car to drift instead of driving straight", solution: "Implemented PWM-based speed calibration in firmware, adjusting each motor's duty cycle individually until straight-line tracking was achieved." },
      { problem: "Understanding the H-bridge logic for controlling motor direction", solution: "Built a truth table mapping each IN1/IN2 pin combination to motor behavior (forward, reverse, brake, coast) and used it as a reference during coding." },
    ],
    specs: {
      "Microcontroller": "Arduino UNO (ATmega328P)",
      "Motor Driver": "L298N Dual H-Bridge",
      "Motors": "4x DC Gear Motors (Yellow)",
      "Wheels": "Mecanum Wheels (omnidirectional)",
      "Chassis": "Blue Acrylic Dual-Layer",
      "Power": "Battery Pack",
      "Programming": "Arduino IDE / C++",
    },
    github: "",
  },
];
